In [ ]:
import pandas as pd

df = pd.read_csv('NIFTY50_1min_01FEB.csv')
df

,Ticker,Date,Timestamp,Open,High,Low,Close,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NIFTY,01-02-2023,09:08:00,17811.60,17811.60,17811.60,17811.60,NaN,NaN,NaN
1,NIFTY,01-02-2023,09:16:00,17815.30,17815.30,17752.50,17787.30,NaN,NaN,NaN
2,NIFTY,01-02-2023,09:17:00,17791.20,17794.45,17777.15,17777.45,min,17361.35000,NaN
3,NIFTY,01-02-2023,09:18:00,17774.95,17782.85,17768.00,17768.85,max,17968.45000,NaN
4,NIFTY,01-02-2023,09:19:00,17767.55,17771.00,17760.80,17769.50,avg,17760.42222,17750.0
...,...,...,...,...,...,...,...,...,...,...
373,NIFTY,01-02-2023,15:28:00,17616.55,17623.45,17616.55,17623.35,NaN,NaN,NaN
374,NIFTY,01-02-2023,15:29:00,17623.65,17623.65,17613.90,17615.10,NaN,NaN,NaN
375,NIFTY,01-02-2023,15:30:00,17615.65,17616.05,17601.65,17605.40,NaN,NaN,NaN
376,NIFTY,01-02-2023,15:31:00,17606.45,17606.45,17606.45,17606.45,NaN,NaN,NaN
377,NIFTY,01-02-2023,15:33:00,17609.80,17622.20,17609.80,17616.30,NaN,NaN,NaN

In [ ]:
import numpy as np
from scipy.stats import norm

class BlackScholes:
    def __init__(self, r=0.07, sigma=0.15):
        self.r = r
        self.sigma = sigma

    def calculate_option_price(self, S, K, T, option_type='call'):
        d1 = (np.log(S / K) + (self.r + 0.5 * self.sigma ** 2) * T) / (self.sigma * np.sqrt(T))
        d2 = d1 - self.sigma * np.sqrt(T)

        if option_type == 'call':
            price = S * norm.cdf(d1) - K * np.exp(-self.r * T) * norm.cdf(d2)
        elif option_type == 'put':
            price = K * np.exp(-self.r * T) * norm.cdf(-d2) - S * norm.cdf(-d1)
        return price

bs_model = BlackScholes()

# Assuming K = 17500
df['BS_Call_Price'] = df['Close'].apply(lambda S: bs_model.calculate_option_price(S, K=17500, T=15/252))
df['BS_Put_Price'] = df['Close'].apply(lambda S: bs_model.calculate_option_price(S, K=17500, T=15/252, option_type='put'))

df

,Ticker,Date,Timestamp,Open,High,Low,Close,Unnamed: 7,Unnamed: 8,Unnamed: 9,BS_Call_Price,BS_Put_Price
0,NIFTY,01-02-2023,09:08:00,17811.60,17811.60,17811.60,17811.60,NaN,NaN,NaN,493.797534,109.432566
1,NIFTY,01-02-2023,09:16:00,17815.30,17815.30,17752.50,17787.30,NaN,NaN,NaN,476.196469,116.131502
2,NIFTY,01-02-2023,09:17:00,17791.20,17794.45,17777.15,17777.45,min,17361.35000,NaN,469.148745,118.933777
3,NIFTY,01-02-2023,09:18:00,17774.95,17782.85,17768.00,17768.85,max,17968.45000,NaN,463.036928,121.421960
4,NIFTY,01-02-2023,09:19:00,17767.55,17771.00,17760.80,17769.50,avg,17760.42222,17750.0,463.497508,121.232540
...,...,...,...,...,...,...,...,...,...,...,...,...
373,NIFTY,01-02-2023,15:28:00,17616.55,17623.45,17616.55,17623.35,NaN,NaN,NaN,365.776491,169.661523
374,NIFTY,01-02-2023,15:29:00,17623.65,17623.65,17613.90,17615.10,NaN,NaN,NaN,360.623236,172.758268
375,NIFTY,01-02-2023,15:30:00,17615.65,17616.05,17601.65,17605.40,NaN,NaN,NaN,354.615598,176.450630
376,NIFTY,01-02-2023,15:31:00,17606.45,17606.45,17606.45,17606.45,NaN,NaN,NaN,355.263223,176.048255
377,NIFTY,01-02-2023,15:33:00,17609.80,17622.20,17609.80,17616.30,NaN,NaN,NaN,361.370311,172.305343